#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
#
Name     : perl-YAML-Tiny
Version  : 1.74
Release  : 50
URL      : https://cpan.metacpan.org/authors/id/E/ET/ETHER/YAML-Tiny-1.74.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/E/ET/ETHER/YAML-Tiny-1.74.tar.gz
Summary  : 'Read/Write YAML files with as little code as possible'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-YAML-Tiny-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This archive contains the distribution YAML-Tiny,
version 1.74:
Read/Write YAML files with as little code as possible

%package dev
Summary: dev components for the perl-YAML-Tiny package.
Group: Development
Provides: perl-YAML-Tiny-devel = %{version}-%{release}
Requires: perl-YAML-Tiny = %{version}-%{release}

%description dev
dev components for the perl-YAML-Tiny package.


%package perl
Summary: perl components for the perl-YAML-Tiny package.
Group: Default
Requires: perl-YAML-Tiny = %{version}-%{release}

%description perl
perl components for the perl-YAML-Tiny package.


%prep
%setup -q -n YAML-Tiny-1.74
cd %{_builddir}/YAML-Tiny-1.74

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/YAML::Tiny.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
